language: python
python:
  - 3.5
sudo: no
env:
  - DJANGO_DEBUG=True PORT=8000 SITE_DOMAIN='http://localhost:8000' DATABASE_URL='postgres://localhost/reservations'
install:
  - pip install -r requirements-dev.txt
before_script:
  - createdb reservations
  - ./manage.py migrate --noinput
script:
  - py.test
