# Note: This config is only for development and contains insecure defaults!
   
volumes:
  reservation-api-data:

services:
  db:
    image: docker.io/postgres:17-alpine
    volumes:
      - reservation-api-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reservation-api"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_DB=reservation-api
      - POSTGRES_USER=reservation-api
      - POSTGRES_PASSWORD=insecure-dev-pg
  web:
    depends_on:
      - db
    build:
      context: .
      args:
        REQUIREMENTS_FILE: "requirements-dev.txt"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./:/code
    environment:
      SECRET_KEY: "insecure-dev-secret"
      DJANGO_DEBUG: "true"
      DATABASE_URL: "postgres://reservation-api:insecure-dev-pg@db/reservation-api"
      ALLOWED_HOST: localhost
    command: "/bin/bash docker/entrypoint-dev.sh"
