# Generated by Django 4.2.16 on 2024-11-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='printer',
            field=models.CharField(choices=[('prusaxl', 'Prusa XL'), ('ultimaker2+', 'Ultimaker 2+')], default='ultimaker2+', help_text='The printer for which a reservation should be added', max_length=255),
            preserve_default=False,
        ),
    ]
