# Generated by Django 4.2.20 on 2025-03-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='printer',
            field=models.CharField(choices=[('prusaxl', 'Prusa XL'), ('ultimaker2+', 'Ultimaker 2+'), ('elegoo-mars', 'Elegoo Mars'), ('elegoo-saturn-4ultra', 'Elegoo Saturn 4 Ultra')], help_text='The printer for which a reservation should be added', max_length=255),
        ),
    ]
